export const ACTIVITY_ACTIONS = {
  GROUP_CREATED: 'GROUP_CREATED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  FRIEND_ADDED: 'FRIEND_ADDED',
  EXPENSE_ADDED: 'EXPENSE_ADDED',
  EXPENSE_DELETED: 'EXPENSE_DELETED',
  SETTLEMENT_COMPLETED: 'SETTLEMENT_COMPLETED'
} as const;
